package com.yuyuedao.yydwechat.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WPKeyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public WPKeyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSidIsNull() {
            addCriterion("sid is null");
            return (Criteria) this;
        }

        public Criteria andSidIsNotNull() {
            addCriterion("sid is not null");
            return (Criteria) this;
        }

        public Criteria andSidEqualTo(Integer value) {
            addCriterion("sid =", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotEqualTo(Integer value) {
            addCriterion("sid <>", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThan(Integer value) {
            addCriterion("sid >", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidGreaterThanOrEqualTo(Integer value) {
            addCriterion("sid >=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThan(Integer value) {
            addCriterion("sid <", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidLessThanOrEqualTo(Integer value) {
            addCriterion("sid <=", value, "sid");
            return (Criteria) this;
        }

        public Criteria andSidIn(List<Integer> values) {
            addCriterion("sid in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotIn(List<Integer> values) {
            addCriterion("sid not in", values, "sid");
            return (Criteria) this;
        }

        public Criteria andSidBetween(Integer value1, Integer value2) {
            addCriterion("sid between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andSidNotBetween(Integer value1, Integer value2) {
            addCriterion("sid not between", value1, value2, "sid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("account_id like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("account_id not like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<String> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<String> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andTextMsgIsNull() {
            addCriterion("text_msg is null");
            return (Criteria) this;
        }

        public Criteria andTextMsgIsNotNull() {
            addCriterion("text_msg is not null");
            return (Criteria) this;
        }

        public Criteria andTextMsgEqualTo(String value) {
            addCriterion("text_msg =", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgNotEqualTo(String value) {
            addCriterion("text_msg <>", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgGreaterThan(String value) {
            addCriterion("text_msg >", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgGreaterThanOrEqualTo(String value) {
            addCriterion("text_msg >=", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgLessThan(String value) {
            addCriterion("text_msg <", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgLessThanOrEqualTo(String value) {
            addCriterion("text_msg <=", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgLike(String value) {
            addCriterion("text_msg like", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgNotLike(String value) {
            addCriterion("text_msg not like", value, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgIn(List<String> values) {
            addCriterion("text_msg in", values, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgNotIn(List<String> values) {
            addCriterion("text_msg not in", values, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgBetween(String value1, String value2) {
            addCriterion("text_msg between", value1, value2, "textMsg");
            return (Criteria) this;
        }

        public Criteria andTextMsgNotBetween(String value1, String value2) {
            addCriterion("text_msg not between", value1, value2, "textMsg");
            return (Criteria) this;
        }

        public Criteria andNewSidIsNull() {
            addCriterion("new_sid is null");
            return (Criteria) this;
        }

        public Criteria andNewSidIsNotNull() {
            addCriterion("new_sid is not null");
            return (Criteria) this;
        }

        public Criteria andNewSidEqualTo(String value) {
            addCriterion("new_sid =", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidNotEqualTo(String value) {
            addCriterion("new_sid <>", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidGreaterThan(String value) {
            addCriterion("new_sid >", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidGreaterThanOrEqualTo(String value) {
            addCriterion("new_sid >=", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidLessThan(String value) {
            addCriterion("new_sid <", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidLessThanOrEqualTo(String value) {
            addCriterion("new_sid <=", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidLike(String value) {
            addCriterion("new_sid like", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidNotLike(String value) {
            addCriterion("new_sid not like", value, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidIn(List<String> values) {
            addCriterion("new_sid in", values, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidNotIn(List<String> values) {
            addCriterion("new_sid not in", values, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidBetween(String value1, String value2) {
            addCriterion("new_sid between", value1, value2, "newSid");
            return (Criteria) this;
        }

        public Criteria andNewSidNotBetween(String value1, String value2) {
            addCriterion("new_sid not between", value1, value2, "newSid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdIsNull() {
            addCriterion("poster_activity_id is null");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdIsNotNull() {
            addCriterion("poster_activity_id is not null");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdEqualTo(Integer value) {
            addCriterion("poster_activity_id =", value, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdNotEqualTo(Integer value) {
            addCriterion("poster_activity_id <>", value, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdGreaterThan(Integer value) {
            addCriterion("poster_activity_id >", value, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("poster_activity_id >=", value, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdLessThan(Integer value) {
            addCriterion("poster_activity_id <", value, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdLessThanOrEqualTo(Integer value) {
            addCriterion("poster_activity_id <=", value, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdIn(List<Integer> values) {
            addCriterion("poster_activity_id in", values, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdNotIn(List<Integer> values) {
            addCriterion("poster_activity_id not in", values, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdBetween(Integer value1, Integer value2) {
            addCriterion("poster_activity_id between", value1, value2, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andPosterActivityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("poster_activity_id not between", value1, value2, "posterActivityId");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidIsNull() {
            addCriterion("draw_activityid is null");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidIsNotNull() {
            addCriterion("draw_activityid is not null");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidEqualTo(Integer value) {
            addCriterion("draw_activityid =", value, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidNotEqualTo(Integer value) {
            addCriterion("draw_activityid <>", value, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidGreaterThan(Integer value) {
            addCriterion("draw_activityid >", value, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidGreaterThanOrEqualTo(Integer value) {
            addCriterion("draw_activityid >=", value, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidLessThan(Integer value) {
            addCriterion("draw_activityid <", value, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidLessThanOrEqualTo(Integer value) {
            addCriterion("draw_activityid <=", value, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidIn(List<Integer> values) {
            addCriterion("draw_activityid in", values, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidNotIn(List<Integer> values) {
            addCriterion("draw_activityid not in", values, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidBetween(Integer value1, Integer value2) {
            addCriterion("draw_activityid between", value1, value2, "drawActivityid");
            return (Criteria) this;
        }

        public Criteria andDrawActivityidNotBetween(Integer value1, Integer value2) {
            addCriterion("draw_activityid not between", value1, value2, "drawActivityid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_p_key
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table w_p_key
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}