package com.yuyuedao.yydwechat.entity;

import java.util.Date;

public class WPKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.account_id
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.text_msg
     *
     * @mbg.generated
     */
    private String textMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.new_sid
     *
     * @mbg.generated
     */
    private String newSid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.poster_activity_id
     *
     * @mbg.generated
     */
    private Integer posterActivityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column w_p_key.draw_activityid
     *
     * @mbg.generated
     */
    private Integer drawActivityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.sid
     *
     * @return the value of w_p_key.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.sid
     *
     * @param sid the value for w_p_key.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.type
     *
     * @return the value of w_p_key.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.type
     *
     * @param type the value for w_p_key.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.keyword
     *
     * @return the value of w_p_key.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.keyword
     *
     * @param keyword the value for w_p_key.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.account_id
     *
     * @return the value of w_p_key.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.account_id
     *
     * @param accountId the value for w_p_key.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.text_msg
     *
     * @return the value of w_p_key.text_msg
     *
     * @mbg.generated
     */
    public String getTextMsg() {
        return textMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.text_msg
     *
     * @param textMsg the value for w_p_key.text_msg
     *
     * @mbg.generated
     */
    public void setTextMsg(String textMsg) {
        this.textMsg = textMsg == null ? null : textMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.new_sid
     *
     * @return the value of w_p_key.new_sid
     *
     * @mbg.generated
     */
    public String getNewSid() {
        return newSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.new_sid
     *
     * @param newSid the value for w_p_key.new_sid
     *
     * @mbg.generated
     */
    public void setNewSid(String newSid) {
        this.newSid = newSid == null ? null : newSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.create_time
     *
     * @return the value of w_p_key.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.create_time
     *
     * @param createTime the value for w_p_key.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.poster_activity_id
     *
     * @return the value of w_p_key.poster_activity_id
     *
     * @mbg.generated
     */
    public Integer getPosterActivityId() {
        return posterActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.poster_activity_id
     *
     * @param posterActivityId the value for w_p_key.poster_activity_id
     *
     * @mbg.generated
     */
    public void setPosterActivityId(Integer posterActivityId) {
        this.posterActivityId = posterActivityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column w_p_key.draw_activityid
     *
     * @return the value of w_p_key.draw_activityid
     *
     * @mbg.generated
     */
    public Integer getDrawActivityid() {
        return drawActivityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column w_p_key.draw_activityid
     *
     * @param drawActivityid the value for w_p_key.draw_activityid
     *
     * @mbg.generated
     */
    public void setDrawActivityid(Integer drawActivityid) {
        this.drawActivityid = drawActivityid;
    }
}